
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
import numpy as np

# Method 1

array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# Method 2 , if huge number range

array_1d_2 = np.arange(10)

array_1d_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [3]:
array_2d = array_1d.reshape((3, 3)) # 1d array as size 10 as it holds ten numbers and is not compatible for 3x3 shape

array_2d

ValueError: cannot reshape array of size 10 into shape (3,3)

In [4]:
# Need to Change size to 9 as 3x3 holds 9

array_1d = np.arange(9)


array_2d = array_1d.reshape((3, 3)) # Now it can be changed as it meets the criteria

array_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Access the element at the second row, second column.


In [5]:
element = array_2d[1, 1]

print("Accessed Element:\n", element)

Accessed Element:
 4


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [6]:
array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

addition = array1 + array2
print("Addition of Arrays\n", addition)

subtraction = array1 - array2
print("Subtraction of Arrays\n", subtraction)

multiplication = array1 * array2
print("Multiplication of Arrays\n", multiplication)

division = array1 / array2
print("Division of Arrays\n", division)

Addition of Arrays
 [5 7 9]
Subtraction of Arrays
 [-3 -3 -3]
Multiplication of Arrays
 [ 4 10 18]
Division of Arrays
 [0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [7]:
array = np.array([1, 2, 3, 4, 5])

sum_of_array = np.sum(array)
print("Sum of Array:\n", sum_of_array)

mean_of_array = np.mean(array)
print("Mean of Array:\n", mean_of_array)

standev_of_array = np.std(array)
print("Standard Deviation of Array:\n", standev_of_array)

Sum of Array:
 15
Mean of Array:
 3.0
Standard Deviation of Array:
 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [8]:
array_1 = np.array([1, 2, 3, 4, 5, 6])

array_2 = array_1.reshape((2, 3))

print("Reshaped Array:\n", array_2)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [9]:
random_array = np.random.randint(0, 100, size=(5, 5))

print("Random Created Array of 5x5 Matrix:\n", random_array)

Random Created Array of 5x5 Matrix:
 [[78 35  3 55 81]
 [39 59 67 26 13]
 [45 73 39 16 66]
 [21 94 16 44 61]
 [24  3 77 13 79]]


Replace all values in the sub-array with a specific value.


In [10]:
# Set slice variable for easy slice and set specific value to change
sub_array_slice = (slice(1,4), slice(1,4))
specific_value = 7

new_specificvalue_subarray = random_array

new_specificvalue_subarray[sub_array_slice] = specific_value

print("Replaced Values Array of 5x5 Matrix:\n", new_specificvalue_subarray)

Replaced Values Array of 5x5 Matrix:
 [[78 35  3 55 81]
 [39  7  7  7 13]
 [45  7  7  7 66]
 [21  7  7  7 61]
 [24  3 77 13 79]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [11]:
array_n = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

array_n_subarray = array_n[[1, 3], :]

print("Extracted Sub-array:\n", array_n_subarray)

Extracted Sub-array:
 [[3 4]
 [7 8]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [12]:
# Method 1 , as randomly as before
arr_2d = np.random.randint(0, 3, size=(3, 3))

print("2D array of Shape (3, 3) with values from 0 to 2 at Random Point:\n", arr_2d)

2D array of Shape (3, 3) with values from 0 to 2 at Random Point:
 [[1 0 0]
 [1 0 0]
 [0 2 2]]


In [13]:
# Method 2, as in position
new_array = np.array([0, 1, 2])

arr_2d = np.tile(new_array, (3, 1))

print("2D array of Shape (3, 3) with values from 0 to 2:\n", arr_2d)

2D array of Shape (3, 3) with values from 0 to 2:
 [[0 1 2]
 [0 1 2]
 [0 1 2]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [14]:
arr_1d = np.array([1, 2, 3])

addition_of_arraybroadcasting = arr_2d + arr_1d

print("Result of Addition Broadcasting:\n", addition_of_arraybroadcasting)

Result of Addition Broadcasting:
 [[1 3 5]
 [1 3 5]
 [1 3 5]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [15]:
random_array_1 = np.random.randint(0, 50, size=(3,3))

random_array_2 = np.random.randint(0, 50, size=(3,3))

print("2D Array 1 of Shape (3, 3) with Random Integers:\n", random_array_1)

print("2D Array 2 of Shape (3, 3) with Random Integers:\n", random_array_2)

2D Array 1 of Shape (3, 3) with Random Integers:
 [[15 34 30]
 [49  4 31]
 [46 18 40]]
2D Array 2 of Shape (3, 3) with Random Integers:
 [[ 3 13 20]
 [33  7 18]
 [25  0 17]]


In [16]:
array_concate_horizontally = np.hstack((random_array_1, random_array_2))

array_concate_vertically = np.vstack((random_array_1, random_array_2))

print("\nHorizontally concatenated Array:\n", array_concate_horizontally)

print("\nVertically concatenated Array:\n", array_concate_vertically)


Horizontally concatenated Array:
 [[15 34 30  3 13 20]
 [49  4 31 33  7 18]
 [46 18 40 25  0 17]]

Vertically concatenated Array:
 [[15 34 30]
 [49  4 31]
 [46 18 40]
 [ 3 13 20]
 [33  7 18]
 [25  0 17]]


In [17]:
split_concate_horizontally = np.hsplit(array_concate_horizontally, 2)

print("\nFirst array after splitback Horizontally:\n", split_concate_horizontally[0])
print("\nSecond array after splitback Horizontally:\n", split_concate_horizontally[1])

split_concate_vertically = np.vsplit(array_concate_vertically, 2)

print("\nFirst array after splitback Vertically:\n", split_concate_vertically[0])
print("\nSecond array after splitback Vertically:\n", split_concate_vertically[1])


First array after splitback Horizontally:
 [[15 34 30]
 [49  4 31]
 [46 18 40]]

Second array after splitback Horizontally:
 [[ 3 13 20]
 [33  7 18]
 [25  0 17]]

First array after splitback Vertically:
 [[15 34 30]
 [49  4 31]
 [46 18 40]]

Second array after splitback Vertically:
 [[ 3 13 20]
 [33  7 18]
 [25  0 17]]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [18]:
array = np.array([1, 2, 1, 2, 3, 4, 5, 6, 8, 9, 1, 2, 2, 22, 21, 1, 1, 1, 1, 2, 5])

number_counts = {}

for num in array:
    if num in number_counts:
        number_counts[num] += 1
    else:
        number_counts[num] = 1
        
number_with_max_count = max(number_counts.values())

mode = [key for key, count in number_counts.items() if count == number_with_max_count]

print("Original Array:\n", array)
print("\nCount of Numbers:\n", number_counts)
print("\nMode:\n", mode)
print("\nCount of Mode:\n", number_with_max_count)

Original Array:
 [ 1  2  1  2  3  4  5  6  8  9  1  2  2 22 21  1  1  1  1  2  5]

Count of Numbers:
 {1: 7, 2: 5, 3: 1, 4: 1, 5: 2, 6: 1, 8: 1, 9: 1, 22: 1, 21: 1}

Mode:
 [1]

Count of Mode:
 7


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

